# For workstations that boot up more slowly than bipartisan progress in the face of an impending government shutdown...
# We see your sudden "Computer will restart in 1 minute" warning and raise you a:
shutdown -a
